#!/bin/sh

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

case "$1" in
"C-x")      xclip -in -filter | tr '\n' ' ' | xclip -in -selection clipboard ;;
"y")      while read file; do xclip -selection clipboard -target image/png "$file"; done ;;
"C-g")      tr '\n' '\0' | xargs -0 gimp & ;;
"C-w")
    while read -r file; do
        TARGET="$HOME/.dotfiles/i3/Wallpaper/Wallpaper"
        rm -f "$TARGET"
        ln -s "$file" "$TARGET"
        rsxiv -B "$file"
        notify-send "Wallpaper Changed" "Set to $file"
    done
    ;;
"C-e")
    while read -r file; do
        cropgui $file
    done
    ;;
"C-a")
    while read -r file; do
        sxat -f $file
    done
    ;;
"d")
    while read -r file; do
        rm $file
    done
    ;;
esac

